### ISSUE TITLE
Problem compiling on Qt 5.5

### ISSUE THREAD

**Issue by theinvisible** [Skycoder42/QTinyAes#1]
Hello,

it seems since your last updates it doesnt compile anymore on Qt 5.5 

Error message:
```
/home/rene/DEV/qtcreator/openfortigui/qtinyaes/qtinyaes.cpp:175: Fehler: no matching function for call to ‘qToBigEndian(quint32, char*)’
     qToBigEndian((quint32)data.size(), dataSize.data());
                                                       ^
/home/rene/DEV/qtcreator/openfortigui/qtinyaes/qtinyaes.cpp:182: Fehler: no matching function for call to ‘qFromBigEndian(const char*)’
     auto dataLen = qFromBigEndian<quint32>(data.constData());
                                                            ^
```
Seems like on Qt 5.7 the function change its parameter type: http://doc.qt.io/qt-5/qtendian.html#qFromBigEndian

Qt 5.5 would be quite important becaue Ubuntu 16.04 uses this version as default.

Cheers
Rene

**Comment by Skycoder42** [comment]
Ah okay. I develop with latest Qt versions, and typically do not assure backward compability. This however is small enough to be adjusted.

**Comment by Skycoder42** [comment]
I updated the code based on the 5.6 documentation. I don't have a Qt Version that old, so please verify this fix does indeed work.

**Comment by theinvisible** [comment]
Thanks, I will give it a try.

**Comment by theinvisible** [comment]
It is working now on 5.5, thanks.

But was there something changed in the implementation? I could not decrypt my existing AES-data, i had to encrypt it again with the new version.

**Comment by Skycoder42** [comment]
I did change the encoding of binary data, because of a bug I found that did not take endianess into account. (Which means data could be incompatible between different devices). The en/decryption process still works the same, but the length of the contained data is encoded in a different way. But this is fixed now, the API (and the encryption process) will stay stable from now on.

If you need to decrypt data from the old format (and have no way around it), please create a different issue for this.
